server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbcache
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

kafka:
  bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
  consumer:
    client-id: kafka-demo-consumer
    group-id: kafka-demo-consumer-group-id-1
    processing-type: batch
    idempotent: true
  topics:
    purchases:
      name: richdemo.customer.purchases.0