server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dbcache
    username: postgres
    password: postgres

kafka:
  bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
  producer:
    strategy: at-most-once
    publishing: async
  topics:
    purchases:
      name: richdemo.customer.purchases.0
      partitions: 3
      replicas: 2