server:
  port: 8081

kafka:
  bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
  producer:
    strategy: at-most-once
    publishing: async
  topics:
    purchases:
      name: richdemo.customer.purchases.0
      partitions: 3
      replicas: 2